### ISSUE TITLE
[Bug]: Wrong /workspace folder contents and cannot reset OpenDevin to a working state with a /workspace folder in sync with the computer /workspace folder

### ISSUE THREAD

**Issue by MarArMar** [OpenHands/OpenHands#2837]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I have a /workspace folder with my work,

On the OpenDevin UI I could see it and all its contents (many files)

I tried OpenDevin on it

OpenDevin tried to create everything from scratch instead of using the existing code

I attempted to stop it but it did not work so I stopped the docker and re started the docker

The docker restarted but now OpenDevin /workspace shows a completely different workspace folder, out of sync with the computer's /workspace folder, with a single and empty .svelte file, which is not at all the content of the /workspace file in my computer

(Clicking on the little "refresh" icon next to the workspace in UI does not solve the problem)

### Current OpenDevin version

```bash
0.7.1
```

### Installation and Configuration

```bash
WORKSPACE_BASE=(absolute path to /workspace folder)
docker run -it \
  --pull=always \
  -e SANDBOX_USER_ID="$(id -u)" \
  -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
  -v $WORKSPACE_BASE:/opt/workspace_base \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -p 3000:3000 \
  --add-host host.docker.internal:host-gateway \
  --name opendevin-app \
  ghcr.io/opendevin/opendevin
```

### Model and Agent

(Any)

### Operating System

Debian 12.5

### Reproduction Steps

1. Install OpenDevin
2. Make it work with a folder with contents in it
3. See that all files / folders inside the /workpace folders are same than the ones in the computer
3. Start a task to work on a projet, OpenDevin starts the task
4. Stop the container
5. Restart Devin
6. See that the workspace folder is now out of sync with the computer one
7. Delete all containers, volumes, image
8. Re install devin from scratch
9. Open OpenDevin
10. See that all files / folders inside the OpenDevin UI /workpace folder are out of sync with the ones in the computer's /workspace folder

**Comment by SmartManoj** [comment]
Could you mention the Operating system?

**Comment by SmartManoj** [comment]
Weird behavior. Could you restart the system and check whether it works?

**Comment by tobitege** [comment]
@MarArMar just to check: do you have a `config.toml` file present?
