### ISSUE TITLE
Usage focused development rather than eval

### ISSUE THREAD

**Issue by rezzie-rich** [OpenHands/OpenHands#3037]
Recently , i conducted an experiment using mentatbot, the 2nd highest ranking ai software agent with an impressive score of 38% on swe-bench lite, which is significantly higher than the current OD score of 26%. Mentatbot was given an issue to implement in a real-world project ( OD PR #2991 ). Upon review, it turned out to be useless and nothing but a waste of $35. Keep in mind that mentatbot also has the capability to analyze the project using a vector database for context awareness. This experiment further supports the point made in discussion #2936. 

Ai developer agents are following the same pattern of llm tuner, aiming to get the highest score, which results in a development motto of eval first and usage later. This motto produces a bunch of broken models and a waste of energy and resources without any practical usability. Instead of testing the capabilities of an agent using evals, it should be tested using real issues to identify what's wrong and improve upon that.

Having a degree means nothing if the holder can't apply those knowledge to work, same as having a higher score means nothing if it can't really code. There should be some issues made for the agents to complete as a test until a PR made by an agent can be merged without further modifications. With each try , we can really figure out what's the main problem is and actually create an agent that WORKS! Otherwise, at the current rate of 2-3% score improvement per updating version, it will take OD +-6 more updates to get to 38%, and still, it won't be useful in practical applications. 

If the agent can create a successful PR, it will automatically score high on eval, but scoring high on eval won't guarantee the creation of a successful PR as proven by the experiment.

**Comment by mamoodi** [comment]
Hello! Although the context of this issue is great, I'm not sure if it's an actionable issue. It's quite a broad and complex topic you are speaking about. Have you considered bringing this up as a discussion in the Slack channel if you are part of that?

**Comment by tobitege** [comment]
> Score means nothing if the agents can't do the only job they're created for. I do think the issue given to mentatbot was something the agent should have been able to execute successfully without requiring any additional modifications with its mighty 38% eval score.

Big picture view for me is this (just speaking for myself): models aren't as capable as we wished they were, and might not be for some while. I think I replied similarly in a different issue of yours, so I won't repeat myself here. 😁

**Comment by mamoodi** [comment]
I don't think anyone is disagreeing with you at all :). Your points are valid and make sense.
All I'm saying is this particular issue is not actionable. It is more suited as a discussion with people. You can say "Make OpenDevin Better" and although that is valid ask, it is not actionable.
