### ISSUE TITLE
[Bug]: LLM retries too fast 

### ISSUE THREAD

**Issue by x66ccff** [OpenHands/OpenHands#4238]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

i'm using docker to start the openhands. In my task, some commands needs long time to execute. (with slow outputs) The agent may regard this as stucked, but in fact it is not. 

the agents tries to retry it frequently. I use this command but these seems useless

**the agent retries every 3 seconds, but i don know how to change this**

```
-e LLM_NUM_RETRIES=20  \
 -e LLM_RETRY_MIN_WAIT=30 \
-e LLM_RETRY_MAX_WAIT=700 \
```

```
docker run -it --pull=never    \
 -e SANDBOX_RUNTIME_CONTAINER_IMAGE=kk-oh-env  \
  -e SANDBOX_USER_ID=$(id -u)   \
  -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
 -e RUN_AS_OPENHANDS=False  \
-e MAX_ITERATIONS=1000  \
-e LLM_NUM_RETRIES=20  \
 -e LLM_RETRY_MIN_WAIT=30 \
-e LLM_RETRY_MAX_WAIT=700 \
-e DEBUG=True \
 -v $WORKSPACE_BASE:/opt/workspace_base  \
   -v /var/run/docker.sock:/var/run/docker.sock    \
 -p 3000:3000     \
--add-host host.docker.internal:host-gateway  \
   --name openhands-app-$(date +%Y%m%d%H%M%S)  \
   ghcr.io/all-hands-ai/openhands:0.9.8
```

### Current OpenHands version

```bash
openhands:0.9.8
```

### Installation and Configuration

```bash
openhands:0.9.8
```

### Model and Agent

qwen2.5:72b

### Operating System

linux

**Comment by enyst** [comment]
@x66ccff Can you please clarify or give an example, what kind of command is being retried too fast?

LLM_*retries variables apply to calls to the LLM, they don't apply to other retries that happen, like those of the runtime environment executing bash commands, etc.
