### ISSUE TITLE
[Bug]: GPT4O not using workspace by default.

### ISSUE THREAD

**Issue by joshms123** [OpenHands/OpenHands#4865]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Try this with both GPT4O and Claude 3.5:
build a hello world script in python, but make it do something unique.

In my tests, GPT4O gives me code output in the chat response, where as Claude actually makes use of the workspace and creates a new file and tests it.
If I tell GPT4O to directly use the workspace, it seems to, but not with the reliability and extra handling that Claude does.

### OpenHands Installation

Docker command in README

### OpenHands Version

0.13.0

### Operating System

WSL on Windows

**Comment by mamoodi** [comment]
Huh... that's really interesting. Wonder if this has something to do with the small tweaks done that changed workspace to repo. I know Claude has been better overall but this seems like a behavior change because GPT4o used to work pretty well at least for writing to a file.
CC @xingyaoww

**Comment by xingyaoww** [comment]
I think this is primarily because GPT-4o might not use the tools well via function calling -- I'm experimenting & evaluating using our old way of prompting for GPT-4o and see how it performs in https://github.com/All-Hands-AI/OpenHands/pull/4711. If it eventually work better, we might switch back there

**Comment by mamoodi** [comment]
Thanks. Hopefully your PR closes this issue 🙏 I'll mark it medium for now but would be good to get this fixed.

**Comment by mamoodi** [comment]
I was also using gpt (I think it was 4o-mini) and I ran into this as well. It would give me the code output but didn't create the files.

**Comment by xingyaoww** [comment]
> I was also using gpt (I think it was 4o-mini) and I ran into this as well. It would give me the code output but didn't create the files.

I think this is the intended behavior - `4o-mini`'s capability is a bit too weak to properly use OpenHands' tool - maybe we should encourage ppl to use stronger model?

**Comment by tobitege** [comment]
I'm not sure that it is too "weak", being in 10th place in LMSys leaderboard and with over 1B tokens on OpenRouter with Cline alone. 🤔
