### ISSUE TITLE
🚀 Auto-Update Model List from OpenRouter API for Latest Choices! 🧠

### ISSUE THREAD

**Issue by champ2050** [OpenHands/OpenHands#4875]
**Feature Request:**

The model dropdown in OpenHands is missing several models available on OpenRouter, such as **Gemini 1.5 Exp**, **Gemini 1.5 Flash**, and others. Additionally, some outdated models still appear in the list, like **Deepseek Coder V2** (which is deprecated by OpenRouter), while the latest model, **Deepseek Coder V2.5**, is not included. To ensure access to all available models, please add functionality to dynamically retrieve model options from the [OpenRouter Models API](https://openrouter.ai/docs/models).

**Proposed Solution:**

- **API Integration**: Fetch model options from OpenRouter's API to auto-populate the dropdown.
- **Automatic Updates**: Update the model list whenever OpenRouter adds new models, eliminating manual updates.
- **Fallback Option**: In case of API issues, revert to a default model list.

**Benefits:**

- **Up-to-date Model Access**: Users get immediate access to new models.
- **Reduced Maintenance**: No need for frequent updates to the model list.

This would make OpenHands more adaptable and useful for model testing.

**Comment by mamoodi** [comment]
Regardless of the models available in the dropdown, you can enabled 'Advanced Options' and then specify your model by typing it out in the box. Therefore it doesn't have to be in the dropdown list. 
However, for greater convenience having up to date model list does make sense.

**Comment by mamoodi** [comment]
https://docs.all-hands.dev/modules/usage/llms/openrouter

Try this for model: openrouter/google/gemini-flash-1.5-exp

See if that works. You likely don't need to set the base url.
