### ISSUE TITLE
Resolver: LLM_MODEL should use "variable" instead of "secret" 

### ISSUE THREAD

**Issue by d-walsh** [OpenHands/OpenHands#5471]
**What problem or use case are you trying to solve?**
Currently it's impossible to see in the Resolver logs what LLM was used and it seems unnecessary to hide it. 

**Describe the UX of the solution you'd like**
Any settings that aren't sensitive should use action "variables" instead of "secrets".

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by enyst** [comment]
This may have been solved already? https://github.com/All-Hands-AI/OpenHands/pull/5278

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12242688257).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5477 has been created. Please review the changes.
