### ISSUE TITLE
The sshd command is not in the image of ghcr.io/opendevin/sandbox:latest

### ISSUE THREAD

**Issue by yehudi-dev** [OpenHands/OpenHands#888]
#### Describe the bug
The frontend need to start the sandbox and use ssh to communicate (by sandbox.py), 
![image](https://github.com/OpenDevin/OpenDevin/assets/4384537/647371c9-25fb-4c94-8cc7-9272e325f4e3)

but `sshd` command is not in container (by image ghcr.io/opendevin/sandbox, id: 1af20fccf49d)
![image](https://github.com/OpenDevin/OpenDevin/assets/4384537/a79ca8d1-6d35-4703-9ad4-60db5cca93c8)

### Current version:
`Commit: 55760ec4ddc669daf4a0b8b36028d2e73c9ab17a`

#### Commands I ran to install and run OpenDevin:

`make run`

**Comment by xingyaoww** [comment]
Please re-pull the image from ghcr again `docker pull ghcr.io/opendevin/sandbox:v0.2` to see if it resolves your issue!

**Comment by yufansong** [comment]
I think the `latest` image should solve the problem.
